name: CI/CD
on:
  push:
    branches: ['main']
    tags: ['v*']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE: tsviliev/3d-printing   # Docker Hub repo
      TAG: prod
      PORTAINER_WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}  # може да липсва засега
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.TAG }}
            ${{ env.IMAGE }}:${{ github.ref_name || 'ci' }}
      - name: Trigger Portainer redeploy (if webhook set)
        if: ${{ env.PORTAINER_WEBHOOK_URL != '' }}
        run: curl -fsSL -X POST "$PORTAINER_WEBHOOK_URL"
