name: CI/CD
on:
  push:
    branches: ['main']
    tags: ['v*']
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            tsviliev/3d-printing/3d-printing-site:prod
            tsviliev/3d-printing/3d-printing-site:${{ github.ref_name || 'ci' }}
      - name: Trigger Portainer redeploy
        run: curl -fsSL -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"
